"use client";

import Image from "next/image";
import { FolderOpen, MoreHorizontal } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { GradientIcon } from "@/components/chat-history-grid";

const companies = [
  { name: "PT Karya Konstruksi Prima - 2024", docs: 120, size: "256 MB" },
  { name: "PT Baja Konstruksi Perkasa", docs: 215, size: "450 MB" },
  { name: "CV Kreasi Digital Nusantara", docs: 88, size: "175 MB" },
];

const recentActivities = [
  {
    name: "Analisis Arus Kas - BKP Q3",
    size: "85 KB",
    type: "xls",
    badge: "Generated by AI",
    icon: "/images/xls-file.png",
    bgColor: "bg-green-50",
  },
  {
    name: "Kontrak_Klien_Baru_2024.pdf",
    size: "1.8 MB",
    type: "pdf",
    badge: "From Document",
    icon: "/images/doc-file.png",
    bgColor: "bg-orange-50",
  },
  {
    name: "PO_Tepung_Terigu_1023.pdf",
    size: "512 KB",
    type: "pdf",
    badge: "Generated by AI",
    icon: "/images/pdf-file.png",
    bgColor: "bg-green-50",
  },
];

const allFiles = [
  {
    name: "Faktur_INV-0821.pdf",
    uploader: "Miska",
    company: "CV Kreasi Digital Nusantara",
    date: "15 Okt 2024",
    type: "Laporan AI",
    fileType: "pdf",
    badge: null,
  },
  {
    name: "Laporan Laba Rugi - KDN Q3.pdf",
    uploader: "Generated by AI",
    company: "PT Baja Konstruksi Perkasa",
    date: "15 Okt 2024",
    type: "Faktur",
    fileType: "pdf",
    badge: "Generated by AI",
  },
  {
    name: "RekKoran_BCA_Okt24.csv",
    uploader: "Miska",
    company: "PT Baja Konstruksi Perkasa",
    date: "14 Okt 2024",
    type: "Laporan Bank",
    fileType: "csv",
    badge: null,
  },
  {
    name: "Data_Gaji_TRMS_Okt.xlsx",
    uploader: "Miska",
    company: "Toko Roti Makmur Sentosa",
    date: "14 Okt 2024",
    type: "Data Internal",
    fileType: "xls",
    badge: null,
  },
  {
    name: "Faktur_DigitalAds_KDN_1024.pdf",
    uploader: "Miska",
    company: "CV Kreasi Digital Nusantara",
    date: "13 Okt 2024",
    type: "Faktur",
    fileType: "pdf",
    badge: null,
  },
  {
    name: "Neraca Keuangan - BKP.pdf",
    uploader: "Generated by AI",
    company: "PT Baja Konstruksi Perkasa",
    date: "12 Okt 2024",
    type: "Laporan AI",
    fileType: "pdf",
    badge: "Generated by AI",
  },
  {
    name: "Perjanjian_Sewa_Ruko_TRMS.docx",
    uploader: "Miska",
    company: "Toko Roti Makmur Sentosa",
    date: "11 Okt 2024",
    type: "Kontrak",
    fileType: "doc",
    badge: null,
  },
  {
    name: "Bukti_Potong_Pph23_BKP.pdf",
    uploader: "Miska",
    company: "PT Baja Konstruksi Perkasa",
    date: "10 Okt 2024",
    type: "Pajak",
    fileType: "pdf",
    badge: null,
  },
  {
    name: "Data_Gaji_TRMS_Okt.xlsx",
    uploader: "Miska",
    company: "PT Baja Konstruksi Perkasa",
    date: "10 Okt 2024",
    type: "Pajak",
    fileType: "xls",
    badge: null,
  },
  {
    name: "Perjanjian_Sewa_Ruko_TRMS.docx",
    uploader: "Miska",
    company: "PT Baja Konstruksi Perkasa",
    date: "10 Okt 2024",
    type: "Pajak",
    fileType: "doc",
    badge: null,
  },
];

const getFileIcon = (fileType: string) => {
  const iconMap = {
    pdf: "/images/pdf-file.png",
    xls: "/images/xls-file.png",
    csv: "/images/xls-file.png",
    doc: "/images/doc-file.png",
  };
  return iconMap[fileType as keyof typeof iconMap] || "📄";
};

const getFileIconBg = (fileType: string) => {
  const bgMap = {
    pdf: "bg-red-50",
    xls: "bg-green-50",
    csv: "bg-green-50",
    doc: "bg-blue-50",
  };
  return bgMap[fileType as keyof typeof bgMap] || "bg-gray-50";
};

export default function VaultPage() {
  return (
    <div className="space-y-6 p-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-semibold text-gray-900 mb-2">
          Arsip Dokumen
        </h1>
        <p className="text-sm text-gray-600">
          Akses semua profil perusahaan dan dokumen di satu tempat
        </p>
      </div>

      {/* Search & Filter */}
      <div className="flex gap-3">
        <div className="relative flex-1 max-w-sm">
          <Input
            placeholder="Search..."
            className="pl-10 bg-white border-gray-200"
          />
          <div className="absolute left-3 top-1/2 -translate-y-1/2">
            <svg
              className="size-4 text-gray-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="m21 21-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </div>
        </div>
        <Button variant="outline" className="bg-white border-gray-200">
          <svg
            className="size-4 mr-2"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.707A1 1 0 013 7V4z"
            />
          </svg>
          Filter
        </Button>
      </div>

      {/* Company Profiles */}
      <div>
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-lg font-semibold text-gray-900">
            Profil Perusahaan
          </h2>
          <Button variant="link" className="text-blue-600 hover:text-blue-700">
            Lihat Semua →
          </Button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {companies.map((company, i) => (
            <Card
              key={i}
              className="cursor-pointer hover:shadow-md transition-shadow bg-white border-gray-200 relative"
            >
              <Button
                variant="ghost"
                size="sm"
                className="absolute top-2 right-2 size-8 p-0 hover:bg-gray-100"
              >
                <MoreHorizontal className="size-4 text-gray-400" />
              </Button>
              <CardContent className="p-4">
                <div className="flex flex-col items-start gap-3">
                  <div className="pl-2 pt-2">
                    <GradientIcon Icon={FolderOpen} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-medium text-gray-900 text-sm mb-2 line-clamp-2">
                      {company.name}
                    </h3>
                    <p className="text-xs text-gray-500">
                      {company.docs} Dokumen • {company.size}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      <div>
        <h2 className="text-lg font-semibold text-gray-900 mb-4">
          Aktivitas Terbaru
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {recentActivities.map((activity, i) => (
            <Card
              key={i}
              className="cursor-pointer hover:shadow-md transition-shadow bg-white border-gray-200 relative"
            >
              <Button
                variant="ghost"
                size="sm"
                className="absolute top-2 right-2 size-8 p-0 hover:bg-gray-100"
              >
                <MoreHorizontal className="size-4 text-gray-400" />
              </Button>
              <CardContent className="p-4">
                {activity.badge && (
                  <Badge
                    variant={
                      activity.badge === "Generated by AI"
                        ? "default"
                        : "secondary"
                    }
                    className={`text-xs mb-3 ${
                      activity.badge === "Generated by AI"
                        ? "bg-green-100 text-green-700 hover:bg-green-200"
                        : "bg-blue-100 text-blue-700 hover:bg-blue-200"
                    }`}
                  >
                    ✓ {activity.badge}
                  </Badge>
                )}
                <div className="flex items-start gap-4">
                  <Image
                    src={activity.icon}
                    alt="icon"
                    width={30}
                    height={30}
                    className="mt-1"
                  />
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start gap-2 mb-2">
                      <h3 className="font-medium text-gray-900 text-sm flex-1 line-clamp-2">
                        {activity.name}
                      </h3>
                    </div>
                    <p className="text-xs text-gray-500 mb-2">
                      {activity.size}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* All Files */}
      <div>
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Semua File</h2>
          <Button variant="link" className="text-blue-600 hover:text-blue-700">
            Lihat Semua →
          </Button>
        </div>
        <Card className="bg-white border-gray-200">
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="border-gray-200">
                    <TableHead className="font-semibold text-gray-700">
                      Nama Dokumen
                    </TableHead>
                    <TableHead className="font-semibold text-gray-700">
                      Diunggah Oleh
                    </TableHead>
                    <TableHead className="font-semibold text-gray-700">
                      Profil Perusahaan
                    </TableHead>
                    <TableHead className="font-semibold text-gray-700">
                      Ukuran File
                    </TableHead>
                    <TableHead className="font-semibold text-gray-700">
                      Tipe Dokumen
                    </TableHead>
                    <TableHead className="w-12" />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {allFiles.map((file, i) => (
                    <TableRow
                      key={i}
                      className="border-gray-100 hover:bg-gray-50"
                    >
                      <TableCell className="py-3">
                        <div className="flex items-center gap-3">
                          <Image
                            src={getFileIcon(file.fileType)}
                            alt="icon"
                            width={30}
                            height={30}
                            className="mt-1"
                          />
                          <div className="flex items-center gap-2">
                            <span className="font-medium text-gray-900 text-sm">
                              {file.name}
                            </span>
                            {file.badge && (
                              <Badge
                                variant="default"
                                className="bg-green-100 text-green-700 hover:bg-green-200 text-xs"
                              >
                                ✓ {file.badge}
                              </Badge>
                            )}
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="py-3">
                        <div className="flex items-center gap-2">
                          {file.uploader === "Generated by AI" ? (
                            <Badge
                              variant="default"
                              className="bg-green-100 text-green-700 hover:bg-green-200 text-xs"
                            >
                              ✓ Generated by AI
                            </Badge>
                          ) : (
                            <>
                              <Avatar className="size-6">
                                <AvatarFallback className="text-xs bg-blue-100 text-blue-700">
                                  {file.uploader.charAt(0)}
                                </AvatarFallback>
                              </Avatar>
                              <span className="text-sm text-gray-700">
                                {file.uploader}
                              </span>
                            </>
                          )}
                        </div>
                      </TableCell>
                      <TableCell className="py-3 text-sm text-gray-700">
                        {file.company}
                      </TableCell>
                      <TableCell className="py-3 text-sm text-gray-700">
                        {file.date}
                      </TableCell>
                      <TableCell className="py-3 text-sm text-gray-700">
                        {file.type}
                      </TableCell>
                      <TableCell className="py-3">
                        <Button
                          variant="ghost"
                          size="sm"
                          className="size-8 p-0 hover:bg-gray-100"
                        >
                          <MoreHorizontal className="size-4 text-gray-400" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
